### ISSUE TITLE
No changes

### ISSUE THREAD

**Issue by Elly-su** [Shpota/github-activity-generator#51]
I've followed all the instructions and done everything that's supposed to be done, I even tried troubleshooting yet nothing as changed.

**Comment by Shpota** [comment]
Please share more details. What error do you get? What OS are you running? What version of Python do you have? What exactly did you do?

**Comment by phoenixtomcat** [comment]
@Shpota @Elly-su I had the same issue as others. I ran it according to instructions and nothing happened, even after 2 hours of waiting. I also did all his troubleshooting and just decided to take the issue into my own hands instead of asking him for help. So I hope both the creator and the rest who have this issue can get some form of help.

The issue predominantly is....if you are a seasoned developer, you should have figured it out by now. And that is the issue with the creator - he assumed everyone should be able to figure it out. But we all started somewhere, and I remember when I was too dumb to understand where to start looking. No harm done, so here it is:

1. The guide he provides on how to call the repo is based on SSH. SSH requires you to enable SSH keys in your profile. I noticed that the .git/logs folder had content that was reflective of what changes the script is doing but in the end none were showing up. So I just created an empty text file and saw if I could manually push it using the same command, but I couldn't because it said Permission denied. I searched online and yep...you need to configure SSH for it. So if you would have done the --help or opened the script itself, you would have seen that the --repository flag can take both SSH or HTTPS. And he provided SSH without thinking that maybe some novices don't know or can't recognize that SSH differs from HTTPS. 

2. The script is hardcoded to force the changes on MAIN branch, whereas my github is naturally started with a MASTER branch. Either change the script to say that or only for this repo, change your master branch name to the one in the script. 

Thanks to the creator. Hope it helps everyone who is stuck 😎

**Comment by Elly-su** [comment]
> Please share more details. What error do you get? What OS are you running? What version of Python do you have? What exactly did you do?

I'm running python 3.12.4, OS is windows 11 and I can't explain exactly what I did because It was kind of long and I used ChatGPT to guide me to solve most of the errors
 I had copied the whole process on my notepad just incase I'd need it later
Do you need me to paste it here to help follow up this issue?

**Comment by Elly-su** [comment]
> @Shpota @Elly-su I had the same issue as others. I ran it according to instructions and nothing happened, even after 2 hours of waiting. I also did all his troubleshooting and just decided to take the issue into my own hands instead of asking him for help. So I hope both the creator and the rest who have this issue can get some form of help.
> 
> The issue predominantly is....if you are a seasoned developer, you should have figured it out by now. And that is the issue with the creator - he assumed everyone should be able to figure it out. But we all started somewhere, and I remember when I was too dumb to understand where to start looking. No harm done, so here it is:
> 
> 1. The guide he provides on how to call the repo is based on SSH. SSH requires you to enable SSH keys in your profile. I noticed that the .git/logs folder had content that was reflective of what changes the script is doing but in the end none were showing up. So I just created an empty text file and saw if I could manually push it using the same command, but I couldn't because it said Permission denied. I searched online and yep...you need to configure SSH for it. So if you would have done the --help or opened the script itself, you would have seen that the --repository flag can take both SSH or HTTPS. And he provided SSH without thinking that maybe some novices don't know or can't recognize that SSH differs from HTTPS.
> 2. The script is hardcoded to force the changes on MAIN branch, whereas my github is naturally started with a MASTER branch. Either change the script to say that or only for this repo, change your master branch name to the one in the script.
> 
> Thanks to the creator. Hope it helps everyone who is stuck 😎

[GitHub activity generator processes.txt](https://github.com/user-attachments/files/17675646/GitHub.activity.generator.processes.txt)   
This is everything I did (I'm a beginner in this stuff btw)

**Comment by phoenixtomcat** [comment]
@Elly-su I noticed something which tripped even me up. Bear with me. In his guide, step 1 says to create an empty repo and not initialize it. Say that we do this and call this repo on our local machine (computer) as "activity repo" or something (which is a folder). Then in step 2, he said to download the script from his repo which is contribute.py. Then a couple of lines down, he says that the script will automatically create its OWN repo and do stuff to it. What's trippy is that if we open up our "activity repo" and in the windows explorer select to show hidden files, we will already see a .git. However, running contribute.py will create another repo within our repo (say, another folder with its own .git file), which complicates things. I think @Shpota needs to address this. 

What does it mean for you? Inside your created repo (e.g. "activity repo") create an empty .txt file. Open git bash or your command prompt:

1. git remote -v  (check to see if the connection to your remote (github) is using HTTPS, not SSH. If it is, you have to change it to HTTPS)

2. git branch (check if the name of your master branch is called master or main - if it's master like mine, do what I said in pt1)

3. git add <name of empty text file> (add the file to staging area, ready to commit )

4. git status (confirm that the file is staged and ready to commit)

5. git commit -m "some message"

6. git push -u origin master(or main, depending on what your master branch is. The names of your remote(on github) and your local machine must match)

7. See if you get any error along the lines of hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

....then comment back and let me know

**Comment by Elly-su** [comment]
> > @Elly-su I noticed something which tripped even me up. Bear with me. In his guide, step 1 says to create an empty repo and not initialize it. Say that we do this and call this repo on our local machine (computer) as "activity repo" or something (which is a folder). Then in step 2, he said to download the script from his repo which is contribute.py. Then a couple of lines down, he says that the script will automatically create its OWN repo and do stuff to it. What's trippy is that if we open up our "activity repo" and in the windows explorer select to show hidden files, we will already see a .git. However, running contribute.py will create another repo within our repo (say, another folder with its own .git file), which complicates things. I think @Shpota needs to address this.
> > What does it mean for you? Inside your created repo (e.g. "activity repo") create an empty .txt file. In the Working directory (folder), Open git bash or your command prompt. You can do this [neat trick](https://www.youtube.com/watch?v=nET1rwpnSE8):
> > 
> > 1. git remote -v  (check to see if the connection to your remote (github) is using HTTPS, not SSH. If it is, you have to change it to HTTPS)
> > 2. git branch (check if the name of your master branch is called master or main - if it's master like mine, do what I said in pt1)
> > 3. git add  (add the file to staging area, ready to commit )
> > 4. git status (confirm that the file is staged and ready to commit)
> > 5. git commit -m "some message"
> > 6. git push -u origin master(or main, depending on what your master branch is. The names of your remote(on github) and your local machine must match)
> > 7. See if you get any error along the lines of hint: Updates were rejected because the remote contains work that you do not
> >    hint: have locally. This is usually caused by another repository pushing to
> >    hint: the same ref. If you want to integrate the remote changes, use
> >    hint: 'git pull' before pushing again.
> >    hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> > 
> > ....then comment back and let me know
> 
> I've followed your well written instructions, Let's wait and see if it works, Thanks Phoenixtomcat!

Hey Ramtin, It didn't work :/ thanks for your help tho! would love to collaborate on a project in future.
